// <auto-generated />
using System;
using MSMS.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MSMS.Server.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240730200735_establishPlaylistRelation")]
    partial class establishPlaylistRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArtistArtistList", b =>
                {
                    b.Property<int>("ArtistListsArtistListId")
                        .HasColumnType("int");

                    b.Property<int>("ArtistsId")
                        .HasColumnType("int");

                    b.HasKey("ArtistListsArtistListId", "ArtistsId");

                    b.HasIndex("ArtistsId");

                    b.ToTable("ArtistArtistList");
                });

            modelBuilder.Entity("MSMS.Server.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArtistDisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArtistSpotifyKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("MSMS.Server.Models.ArtistList", b =>
                {
                    b.Property<int>("ArtistListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtistListId"));

                    b.Property<string>("ArtistListName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ArtistListId");

                    b.ToTable("ArtistLists");
                });

            modelBuilder.Entity("MSMS.Server.Models.SpotifyPlaylist", b =>
                {
                    b.Property<string>("SpotifyPlaylistId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ArtistListId")
                        .HasColumnType("int");

                    b.Property<string>("PlaylistKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpotifyPlaylistName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpotifyPlaylistId");

                    b.HasIndex("ArtistListId")
                        .IsUnique();

                    b.ToTable("SpotifyLists");
                });

            modelBuilder.Entity("ArtistArtistList", b =>
                {
                    b.HasOne("MSMS.Server.Models.ArtistList", null)
                        .WithMany()
                        .HasForeignKey("ArtistListsArtistListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSMS.Server.Models.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MSMS.Server.Models.SpotifyPlaylist", b =>
                {
                    b.HasOne("MSMS.Server.Models.ArtistList", "LinkedArtistList")
                        .WithOne("LinkedPlaylist")
                        .HasForeignKey("MSMS.Server.Models.SpotifyPlaylist", "ArtistListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkedArtistList");
                });

            modelBuilder.Entity("MSMS.Server.Models.ArtistList", b =>
                {
                    b.Navigation("LinkedPlaylist");
                });
#pragma warning restore 612, 618
        }
    }
}
